# Install and import pandas

In [ ]:
!pip install pandas
# Requirement already satisfied: package already installed

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In order to use any library in Python, you must first import that library.

In [ ]:
import pandas as pd
# as pd is the shortname

In [ ]:
pd.__version__
# check version

'2.2.2'

We will import student file using read_excel or read_csv functions.

In [ ]:
# import student excel file
pd.read_excel("student.xlsx")

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# import student csv file
pd.read_csv("student.csv")

In [ ]:
import sys
sys.getsizeof(df)

6363

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("student.xlsx")
# df is short for dataframe.
# this code will save student file in df

In [ ]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

# Inspecting and Exploring Dataframe

In [ ]:
# top 5 rows
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# top 10 rows
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
df.head(3)

   id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [ ]:
# last 5 rows
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.tail(7)

    id         name  class  mark  gender
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# random sample data
df.sample()

    id        name class  mark  gender
20  21  Babby John  Four    69  female

In [ ]:
# random sample data
df.sample()

   id        name class  mark  gender
3   4  Krish Star  Four    60  female

In [ ]:
df.sample(5)

    id         name  class  mark  gender
7    8       Asruid   Five    85    male
19  20       Jackly   Nine    65  female
24  25     Giff Tow  Seven    88    male
28  29  Tess Played  Seven    55    male
14  15     Tade Row    NaN    88    male

In [ ]:
df.sample?
# help on sample method
# open docstring

In [ ]:
df.head?

In [ ]:
# number of rows and columns
df.shape
# 35 rows and 5 column
# .shape doesnt take (). its an attribute
# .sample() is a method

(35, 5)

### Method vs. Attribute in Pandas

In object-oriented programming (which pandas is built upon), objects (like your DataFrame `df`) have both **attributes** and **methods**.

*   **Attributes**: These are characteristics or properties of an object. They store data or provide information about the object's state. You access them directly without parentheses.
    *   **Example**: `df.shape` is an attribute that returns a tuple representing the dimensions (rows, columns) of the DataFrame. `df.index` or `df.columns` are also attributes.

*   **Methods**: These are functions that belong to an object. They perform actions, operations, or calculations on the object's data. You call them using parentheses `()` (even if they don't take any arguments).
    *   **Example**: `df.head()` is a method that returns the first `n` rows of the DataFrame. `df.sample()` and `df.info()` are also methods.

In [ ]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

Compare non-null count vs number of entries. if non-null count is different then number of entries, there is a missing value on that column.
- name has 1 missing value
- class has 1 missing value
- gender has 2 missing values

Check datatype for each column. Object is string datatype.

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# name of the columns
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
# statistical summary
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

- mean should be bigger then std (standard deviation).
- 50% is median. In the mark 50% of all student have their mark => 79. 50% of all student have <79.
- 25% of all students have their mark <62.5

In [ ]:
# number of rows
len(df)

35

In [ ]:
# rows * columns
df.size
# 35 * 5

175

In [ ]:
# datatypes of the columns
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
df.isnull()

       id   name  class   mark  gender
0   False  False  False  False   False
1   False  False  False  False   False
2   False  False  False  False   False
3   False  False  False  False   False
4   False  False  False  False   False
5   False  False  False  False   False
6   False  False  False  False   False
7   False  False  False  False   False
8   False  False  False  False    True
9   False  False  False  False   False
10  False  False  False  False   False
11  False  False  False  False   False
12  False  False  False  False   False
13  False  False  False  False   False
14  False  False   True  False   False
15  False  False  False  False   False
16  False  False  False  False   False
17  False  False  False  False   False
18  False  False  False  False   False
19  False  False  False  False   False
20  False  False  False  False   False
21  False  False  False  False   False
22  False  False  False  False   False
23  False  False  False  False   False
24  False  False  False  False   False
25  False  False  False  False   False
26  False   True  False  False    True
27  False  False  False  False   False
28  False  False  False  False   False
29  False  False  False  False   False
30  False  False  False  False   False
31  False  False  False  False   False
32  False  False  False  False   False
33  False  False  False  False   False
34  False  False  False  False   False

In [ ]:
# Counts missing values per column.
df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
# total missing values in df.
df.isnull().sum().sum()

np.int64(4)

# Subsetting DataFrame
- accessing columns and rows

use [] (slicing method) to  access and return the columns

In [ ]:
# return only name column and all rows
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df["class"]

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14      NaN
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, dtype: object

you can use . notation to return columns.

In [ ]:
df.name

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.class
# this will fail. because class is a reserved keyword in python.

SyntaxError: invalid syntax (1584895042.py, line 1)

In [ ]:
df["gender"]

0     female
1       male
2       male
3     female
4     female
5       male
6       male
7       male
8        NaN
9     female
10    female
11    female
12    female
13    female
14      male
15      male
16      male
17      male
18      male
19    female
20    female
21    female
22      male
23      male
24      male
25      male
26       NaN
27    female
28      male
29    female
30      male
31    female
32    female
33      male
34    female
Name: gender, dtype: object

In [ ]:
df.gender

0     female
1       male
2       male
3     female
4     female
5       male
6       male
7       male
8        NaN
9     female
10    female
11    female
12    female
13    female
14      male
15      male
16      male
17      male
18      male
19    female
20    female
21    female
22      male
23      male
24      male
25      male
26       NaN
27    female
28      male
29    female
30      male
31    female
32    female
33      male
34    female
Name: gender, dtype: object

if you want to return multiples. you must use []. provide the list of the column name

list objects are created using []

In [ ]:
# name and class
df[["name", "class"]]
# inner [] is list of the column names. ["name", "class"]
# outer [] is for slicing.

           name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
5     Alex John   Four
6   My John Rob  Fifth
7        Asruid   Five
8       Tes Qry    Six
9      Big John   Four
10       Ronald    Six
11        Recky    Six
12          Kty  Seven
13         Bigy  Seven
14     Tade Row    NaN
15        Gimmy   Four
16        Tumyu    Six
17        Honny   Five
18        Tinny   Nine
19       Jackly   Nine
20   Babby John   Four
21       Reggid  Seven
22        Herod  Eight
23    Tiddy Now  Seven
24     Giff Tow  Seven
25       Crelea  Seven
26          NaN  Three
27    Rojj Base  Seven
28  Tess Played  Seven
29    Reppy Red    Six
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

In [ ]:
df["name"].head(3)

0    John Deo
1    Max Ruin
2      Arnold
Name: name, dtype: object

In [ ]:
df["class"].sample(3)

23    Seven
26    Three
22    Eight
Name: class, dtype: object

In [ ]:
df["mark"].median()

79.0

In [ ]:
df["mark"].min()

18

In [ ]:
df["mark"].max()

96

In [ ]:
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
df[["name", "class"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    34 non-null     object
 1   class   34 non-null     object
dtypes: object(2)
memory usage: 692.0+ bytes

In [ ]:
df[["name", "class"]].sample()

     name  class
22  Herod  Eight

# loc and iloc operator

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.iloc[22]

id           23
name      Herod
class     Eight
mark         79
gender     male
Name: 22, dtype: object

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

df.loc[rows, column labels]

In [ ]:
df.loc[0, "name"]

'John Deo'

In [ ]:
df.loc[3, "mark"]

np.int64(60)

In [ ]:
# names of first 5 students
df.loc[0:4, "name"]

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [ ]:
df.loc[11:14, "name"]

11       Recky
12         Kty
13        Bigy
14    Tade Row
Name: name, dtype: object

In [ ]:
df.loc[11:14, ["name", "class"]]

        name  class
11     Recky    Six
12       Kty  Seven
13      Bigy  Seven
14  Tade Row    NaN

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
# name of the first
# df.loc[0, "name"]
df.iloc[0, 1]

'John Deo'

In [ ]:
# df.loc[3, "mark"]
df.iloc[3, 3]

np.int64(60)

In [ ]:
# df.loc[11:14, ["name", "class"]]
df.iloc[11:15, [1,2]]

        name  class
11     Recky    Six
12       Kty  Seven
13      Bigy  Seven
14  Tade Row    NaN

- loc operator is inclusive of stopping index.
- iloc operator will exclude the stopping index in the output.

In [ ]:
df.iloc[11:15, 0:2]
# selection of row and column index
# this code will return row indexes 11,12,13 and 14. and also column indexes 0 and 1.

    id      name
11  12     Recky
12  13       Kty
13  14      Bigy
14  15  Tade Row

# Filtering Dataframe

- df[condition]

In [ ]:
# Return student with mark >=90
df[df["mark"]>=90]

    id       name  class  mark  gender
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
32  33  Kenn Rein    Six    96  female

In [ ]:
# Return class Five
df[df["class"]=="Five"]
# first df[] is used for slicing
# second df[] is criteria

    id    name class  mark gender
7    8  Asruid  Five    85   male
17  18   Honny  Five    75   male

In [ ]:
# Return class not Five
df[~(df["class"]=="Five")]
# first df[] is used for slicing
# second df[] is criteria

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# Return class not Five
df[df["class"]!="Five"]
# first df[] is used for slicing
# second df[] is criteria

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
# Return female student at class Four
df[(df["gender"]=="female") & (df["class"]=="Four")]

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
20  21  Babby John  Four    69  female

- blue [] is slicing
- brown [] is condition

In [ ]:
# Return female student or student class Four
df[(df["gender"]=="female") | (df["class"]=="Four")]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
15  16        Gimmy   Four    88    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [ ]:
# Return student with mark >=90
# df[df["mark"]>=90]
df.loc[df["mark"]>=90, :]
# : means return entire range

    id       name  class  mark  gender
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
32  33  Kenn Rein    Six    96  female

In [ ]:
# df.iloc[df["mark"]>=90, :]

In [ ]:
# Return female student at class Four
# df[(df["gender"]=="female") & (df["class"]=="Four")]
df.loc[(df["gender"]=="female") & (df["class"]=="Four"), :]

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
20  21  Babby John  Four    69  female

In [ ]:
df.filter(items=['name', 'mark'])

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.filter(like='ma')
#filter colum names

    mark
0     75
1     85
2     55
3     60
4     60
5     55
6     78
7     85
8     78
9     55
10    89
11    94
12    88
13    88
14    88
15    88
16    54
17    75
18    18
19    65
20    69
21    55
22    79
23    78
24    88
25    79
26    81
27    86
28    55
29    79
30    88
31    90
32    96
33    69
34    88

In [ ]:
df.query("mark > 60")

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.query('gender == "male"')

    id         name  class  mark gender
1    2     Max Ruin  Three    85   male
2    3       Arnold  Three    55   male
5    6    Alex John   Four    55   male
6    7  My John Rob  Fifth    78   male
7    8       Asruid   Five    85   male
14  15     Tade Row    NaN    88   male
15  16        Gimmy   Four    88   male
16  17        Tumyu    Six    54   male
17  18        Honny   Five    75   male
18  19        Tinny   Nine    18   male
22  23        Herod  Eight    79   male
23  24    Tiddy Now  Seven    78   male
24  25     Giff Tow  Seven    88   male
25  26       Crelea  Seven    79   male
28  29  Tess Played  Seven    55   male
30  31  Marry Toeey   Four    88   male
33  34     Gain Toe  Seven    69   male

# Sort values

In [ ]:
# Sorting by names
df.loc[:,:].sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
# Sorting by mark
df.loc[:,:].sort_values(by="mark")

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
28  29  Tess Played  Seven    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
23  24    Tiddy Now  Seven    78    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
# Sorting by mark in desc
df.loc[:,:].sort_values(by="mark", ascending=False).head()

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male

In [ ]:
df[["name", "class"]].sort_values(by="class").head()

           name  class
22        Herod  Eight
6   My John Rob  Fifth
17        Honny   Five
7        Asruid   Five
30  Marry Toeey   Four

In [ ]:
# return student who are female and at class seven
df[(df["gender"]=="female") & (df["class"]=="Seven")].sort_values(by="mark")

    id       name  class  mark  gender
21  22     Reggid  Seven    55  female
27  28  Rojj Base  Seven    86  female
13  14       Bigy  Seven    88  female
12  13        Kty  Seven    88  female
31  32  Binn Rott  Seven    90  female

In [ ]:
# return student who are female and at class seven
df[(df["gender"]=="female") & (df["class"]=="Seven")].sort_values(by="mark", ascending=False)

    id       name  class  mark  gender
31  32  Binn Rott  Seven    90  female
12  13        Kty  Seven    88  female
13  14       Bigy  Seven    88  female
27  28  Rojj Base  Seven    86  female
21  22     Reggid  Seven    55  female

In [ ]:
df.sort_values(by = ["mark", "name"]).head()

    id       name  class  mark  gender
18  19      Tinny   Nine    18    male
16  17      Tumyu    Six    54    male
5    6  Alex John   Four    55    male
2    3     Arnold  Three    55    male
9   10   Big John   Four    55  female

In [ ]:
df.sort_values(by = ["mark", "name"], ascending=[False,True]).head()

    id       name  class  mark  gender
32  33  Kenn Rein    Six    96  female
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
10  11     Ronald    Six    89  female
13  14       Bigy  Seven    88  female

# Value counts

In [ ]:
## How many male and female students are there?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
## Class and number of student
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64