# Intro to Pandas
by Ryan Orsinger

## Introducing DataFrames

### Pandas DataFrames Basics - Part 1
- How to make pandas DataFrames from other Python collections
- Learning about your dataframe's properties and information
- Selecting a single column
- Adding new columns to a DataFrame
- Renaming columns
- Descriptive stats on the columns

In [ ]:
import pandas as pd

In [ ]:
# Creating a dataframe from a list of dictionaries
basket = [ {"item": "mango", "quantity": 4, "price": 2.99},
 {"item": "bread", "quantity": 2, "price": 3.25},
  {"item": "juice", "quantity": 1, "price": 5.90},
   {"item": "orange", "quantity": 3, "price": 2.99},
    {"item": "lime", "quantity": 3, "price": 0.3},
]
basket

[{'item': 'mango', 'quantity': 4, 'price': 2.99},
 {'item': 'bread', 'quantity': 2, 'price': 3.25},
 {'item': 'juice', 'quantity': 1, 'price': 5.9},
 {'item': 'orange', 'quantity': 3, 'price': 2.99},
 {'item': 'lime', 'quantity': 3, 'price': 0.3}]

In [ ]:
# With dataframes, our columns are our variables or features
# Each row represents a unique observation (usually)
df = pd.DataFrame(basket)
df

     item  quantity  price
0   mango         4   2.99
1   bread         2   3.25
2   juice         1   5.90
3  orange         3   2.99
4    lime         3   0.30

In [ ]:
# Creating a dataframe from a dictionary of lists
basket = {
    "item": ["mango", "bread", "juice", "orange", "lime"],
    "quantity": [4, 2, 1, 3, 3],
    "price": [2.99, 3.25, 5.90, 2.99, 0.30]
}
basket

{'item': ['mango', 'bread', 'juice', 'orange', 'lime'],
 'quantity': [4, 2, 1, 3, 3],
 'price': [2.99, 3.25, 5.9, 2.99, 0.3]}

In [ ]:
pd.DataFrame(basket)

     item  quantity  price
0   mango         4   2.99
1   bread         2   3.25
2   juice         1   5.90
3  orange         3   2.99
4    lime         3   0.30

In [ ]:
# Creating a dataframe from a list of lists
example = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

column_names = ["variable_a", "variable_b", "variable_c"]
row_names = ["observation_1", "observation_2", "observation_3"]

pd.DataFrame(example, columns=column_names, index=row_names)

               variable_a  variable_b  variable_c
observation_1           1           2           3
observation_2           4           5           6
observation_3           7           8           9

In [ ]:
# Creating an empty dataframe
df = pd.DataFrame()

# Adding columns to a dataframe
# Any list-like data type can become a column
df["item"] = pd.Series(["Mango", "Bread", "Juice", "Orange", "Lime"]) #pandas series
df["quantity"] = [2, 2, 1, 3, 3] # list
df["price"] = (2.99, 3.25, 5.90, 2.99, 0.30) # tuple
df

     item  quantity  price
0   Mango         2   2.99
1   Bread         2   3.25
2   Juice         1   5.90
3  Orange         3   2.99
4    Lime         3   0.30

In [ ]:
# .shape returns rows, columns
df.shape

(5, 3)

In [ ]:
# Returns the rows
df.shape[0]

5

In [ ]:
# Returns the number of columns
df.shape[1]

3

In [ ]:
# len returns number of rows
len(df)

5

In [ ]:
# size returns rows * columns
df.size
# 5 * 3 = 15

15

In [ ]:
# Adding new columns to the dataframe
df["subtotal"] = df["quantity"] * df["price"]
df

     item  quantity  price  subtotal
0   Mango         2   2.99      5.98
1   Bread         2   3.25      6.50
2   Juice         1   5.90      5.90
3  Orange         3   2.99      8.97
4    Lime         3   0.30      0.90

In [ ]:
# set_index can overwrite the default index
df.set_index("item", inplace=True)
df

        quantity  price  subtotal
item
Mango          2   2.99      5.98
Bread          2   3.25      6.50
Juice          1   5.90      5.90
Orange         3   2.99      8.97
Lime           3   0.30      0.90

In [ ]:
# Accessing the index values
df.index

Index(['Mango', 'Bread', 'Juice', 'Orange', 'Lime'], dtype='object', name='item')

In [ ]:
# We can also overwrite the index with a Series of equal length
df.index = df.index.str.lower()
df

        quantity  price  subtotal
item
mango          2   2.99      5.98
bread          2   3.25      6.50
juice          1   5.90      5.90
orange         3   2.99      8.97
lime           3   0.30      0.90

In [ ]:
# Accessing all the columns
df.columns

Index(['quantity', 'price', 'subtotal'], dtype='object')

In [ ]:
# Another example of creating a new column
df["tax"] = 0.07
df

        quantity  price  subtotal   tax
item
mango          2   2.99      5.98  0.07
bread          2   3.25      6.50  0.07
juice          1   5.90      5.90  0.07
orange         3   2.99      8.97  0.07
lime           3   0.30      0.90  0.07

In [ ]:
# The "total cost" column does not exist, but this bracket syntax creates it.
df["total cost"] = df["subtotal"] + (df["subtotal"] * df["tax"])
df

        quantity  price  subtotal   tax  total cost
item
mango          2   2.99      5.98  0.07      6.3986
bread          2   3.25      6.50  0.07      6.9550
juice          1   5.90      5.90  0.07      6.3130
orange         3   2.99      8.97  0.07      9.5979
lime           3   0.30      0.90  0.07      0.9630

In [ ]:
# Dot syntax also allows for calling an existing column
# Using .column syntax only works if the column exists already, has no spaces, and is not a dataframe method already
df.price

item
mango     2.99
bread     3.25
juice     5.90
orange    2.99
lime      0.30
Name: price, dtype: float64

In [ ]:
df.subtotal

item
mango     5.98
bread     6.50
juice     5.90
orange    8.97
lime      0.90
Name: subtotal, dtype: float64

In [ ]:
# .dtypes outputs the datatypes of all columns in the dataframe
df.dtypes

quantity        int64
price         float64
subtotal      float64
tax           float64
total cost    float64
dtype: object

In [ ]:
# .info returns datatype and non-null count
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, mango to lime
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   quantity    5 non-null      int64
 1   price       5 non-null      float64
 2   subtotal    5 non-null      float64
 3   tax         5 non-null      float64
 4   total cost  5 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 412.0+ bytes

In [ ]:
df.price.describe()
# 25% 1st quarter
# 75% 3rd querter
# 50% median
# std = standart deviation

count    5.000000
mean     3.086000
std      1.982783
min      0.300000
25%      2.990000
50%      2.990000
75%      3.250000
max      5.900000
Name: price, dtype: float64

In [ ]:
df.price

item
mango     2.99
bread     3.25
juice     5.90
orange    2.99
lime      0.30
Name: price, dtype: float64

In [ ]:
# Show descriptive stats for numeric columns
df.describe()

       quantity     price  subtotal   tax  total cost
count   5.00000  5.000000  5.000000  5.00    5.000000
mean    2.20000  3.086000  5.650000  0.07    6.045500
std     0.83666  1.982783  2.935933  0.00    3.141448
min     1.00000  0.300000  0.900000  0.07    0.963000
25%     2.00000  2.990000  5.900000  0.07    6.313000
50%     2.00000  2.990000  5.980000  0.07    6.398600
75%     3.00000  3.250000  6.500000  0.07    6.955000
max     3.00000  5.900000  8.970000  0.07    9.597900

In [ ]:
# A column in a dataframe is a series
type(df.quantity)

pandas.core.series.Series

In [ ]:
# .value_counts returns a series
df.quantity.value_counts()

quantity
2    2
3    2
1    1
Name: count, dtype: int64

In [ ]:
# Aggregate functions can run on all the numeric values in the dataframe
df.mean()

quantity      2.2000
price         3.0860
subtotal      5.6500
tax           0.0700
total cost    6.0455
dtype: float64

In [ ]:
# Obtain the median of all numeric columns
df.median()

quantity      2.0000
price         2.9900
subtotal      5.9800
tax           0.0700
total cost    6.3986
dtype: float64

In [ ]:
# Standard deviation of all the numeric columns
df.std()

quantity      0.836660
price         1.982783
subtotal      2.935933
tax           0.000000
total cost    3.141448
dtype: float64

In [ ]:
# The square bracket syntax can be used to access column names with spaces
# Same with column names that are methods on the dataframe object
# Recommend avoiding column names with spaces, removing spaces when you encounter them
# Recommend avoiding naming columns after dataframe method
df["shape"] = ["round", "loaf", "jug", "round", "round"]
df

        quantity  price  subtotal   tax  total cost  shape
item
mango          2   2.99      5.98  0.07      6.3986  round
bread          2   3.25      6.50  0.07      6.9550   loaf
juice          1   5.90      5.90  0.07      6.3130    jug
orange         3   2.99      8.97  0.07      9.5979  round
lime           3   0.30      0.90  0.07      0.9630  round

In [ ]:
# Remember that the .shape attribute shows # rows, #columns
df.shape

(5, 6)

In [ ]:
# The bracket quote syntax returns the column
df["shape"]

item
mango     round
bread      loaf
juice       jug
orange    round
lime      round
Name: shape, dtype: object

In [ ]:
# Naming columns the same as built-in dataframe methods and spaces in column names are not helpful
# .rename allows for renaming columns in a dataframe using a dictionary
df.rename(columns={"shape": "item_shape", "total cost": "total"}, inplace=True)
df

        quantity  price  subtotal   tax   total item_shape
item
mango          2   2.99      5.98  0.07  6.3986      round
bread          2   3.25      6.50  0.07  6.9550       loaf
juice          1   5.90      5.90  0.07  6.3130        jug
orange         3   2.99      8.97  0.07  9.5979      round
lime           3   0.30      0.90  0.07  0.9630      round

## Exercises
- Assign dataframe named `df` out of the following list of dictionaries.
```
items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]
```
- Rename the `item name` column to `item_name`
- Add a column named `units_sold` to this dataframe and assign the values `[41, 113, 54, 35, 22]`
- Convert the price column into a float (hint: remove non-numeric characters before attempting to convert the data type to a float)
- Create a new column named `total_revenue` that holds the `price` column times the `units_sold` column
- Round the `total_revenue` column values to the nearest whole number. (hint: search or consult the pandas documentation

In [ ]:
import pandas as pd

In [ ]:
# Assign dataframe named `df` out of the following list of dictionaries

items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]
df = pd.DataFrame(items)
df

   item name   price            type
0  USB cable  $10.99  USB C to USB C
1  USB cable  $10.99  USB A to USB C
2  Batteries   $9.99              AA
3  Batteries   $8.99             AAA
4      Mouse  $12.99    Wireless USB

In [ ]:
# Rename the item name column to item_name

df.rename(columns={"item name": "item_name"}, inplace=True)
df

   item_name   price            type
0  USB cable  $10.99  USB C to USB C
1  USB cable  $10.99  USB A to USB C
2  Batteries   $9.99              AA
3  Batteries   $8.99             AAA
4      Mouse  $12.99    Wireless USB

In [ ]:
# Add a column named units_sold to this dataframe and assign the values [41, 113, 54, 35, 22]

df["units_sold"] = [41, 113, 54, 35, 22]
df

   item_name   price            type  units_sold
0  USB cable  $10.99  USB C to USB C          41
1  USB cable  $10.99  USB A to USB C         113
2  Batteries   $9.99              AA          54
3  Batteries   $8.99             AAA          35
4      Mouse  $12.99    Wireless USB          22

In [ ]:
# Convert the price column into a float data type. First replace $ and then convert to folat.

df["price"] = df["price"].str.replace("$", "", regex=False).astype(float)
df

   item_name  price            type  units_sold
0  USB cable  10.99  USB C to USB C          41
1  USB cable  10.99  USB A to USB C         113
2  Batteries   9.99              AA          54
3  Batteries   8.99             AAA          35
4      Mouse  12.99    Wireless USB          22

In [ ]:
# Create a new column named "total_revenue" that holds the `price` column times the `units_sold` column

df["total_revenue"] = df["price"] * df["units_sold"]
df

   item_name  price            type  units_sold  total_revenue
0  USB cable  10.99  USB C to USB C          41         450.59
1  USB cable  10.99  USB A to USB C         113        1241.87
2  Batteries   9.99              AA          54         539.46
3  Batteries   8.99             AAA          35         314.65
4      Mouse  12.99    Wireless USB          22         285.78

In [ ]:
# Round the total_revenue column values to the nearest whole number.

df["total_revenue"] = df["total_revenue"].round(0)
df

   item_name  price            type  units_sold  total_revenue
0  USB cable  10.99  USB C to USB C          41          451.0
1  USB cable  10.99  USB A to USB C         113         1242.0
2  Batteries   9.99              AA          54          539.0
3  Batteries   8.99             AAA          35          315.0
4      Mouse  12.99    Wireless USB          22          286.0

In [ ]:
# export file in csv

df.to_csv("electronics_sales.csv", index=False)
print("Saved as CSV!")

Saved as CSV!

In [ ]:
# export file in excel

df.to_excel("electronics_sales.xlsx", index=False)
print("Saved as Excel!")

Saved as Excel!